Re-add Datomic, but exclude Jetty
This was humbling--spent a long time figuring out why I was getting
java.lang.NoClassDefFoundERror when running the webserver, and realized
that this project depends on a more recent version of Jetty (through
ring) than Datomic. Removing the version of Jetty used by Datomic (per
[1]) fixes all this.

[1] https://docs.datomic.com/cloud/troubleshooting.html#troubleshooting-clients